# Generated by Django 4.1.3 on 2022-12-20 10:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cas_proxy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionticket',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='sessionticket',
            name='logged_in',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
