# Generated by Django 4.1.3 on 2022-11-14 09:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('commons', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_of_appointment', models.PositiveSmallIntegerField(default=0)),
                ('address_city', models.CharField(max_length=64)),
                ('address_line', models.CharField(max_length=128)),
                ('address_number', models.CharField(max_length=32)),
                ('address_zip_code', models.CharField(max_length=32)),
                ('telephone', models.CharField(blank=True, max_length=32)),
                ('mobile', models.CharField(blank=True, max_length=32)),
                ('status', models.CharField(choices=[('DRAFT', 'Πρόχειρη'), ('DELETED', 'Διαγραμμένη'), ('SUBMITTED', 'Υποβεβλημένη'), ('UNDER_REVIEW', 'Υπο Εξέταση'), ('FINALIZED', 'Καταχωρημένη/Αποδεκτή'), ('CANCELLED', 'Ακυρωμένη')], default='DRAFT', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('work_experience_years', models.PositiveSmallIntegerField(default=0)),
                ('work_experience_months', models.PositiveSmallIntegerField(default=0)),
                ('work_experience_days', models.PositiveSmallIntegerField(default=0)),
                ('work_together', models.BooleanField(default=False, help_text='Συνυπηρέτηση')),
                ('locality', models.BooleanField(default=False, help_text='Εντοπιότητα')),
                ('married', models.BooleanField(default=False, help_text='Έγγαμος')),
                ('divorced', models.BooleanField(default=False, help_text='Διαζευγμένος')),
                ('separated', models.BooleanField(default=False, help_text='Σε Διάσταση')),
                ('widowhood', models.BooleanField(default=False, help_text='Σε Χηρεία')),
                ('single_parent_family', models.BooleanField(default=False, help_text='Μονογονεϊκη Οικογένεια')),
                ('number_of_children', models.PositiveSmallIntegerField(default=0, help_text='Αριθμός Τέκνων')),
                ('child_custody', models.BooleanField(default=False, help_text='Επιμέλεια Τέκνων')),
                ('minor_child', models.BooleanField(default=False, help_text='Ανήλικο Τέκνο')),
                ('health_issues', models.CharField(choices=[('FROM_50_TO_66', 'Αναπηρία 50-66%'), ('FROM_67_TO_79', 'Αναπηρία 67-79%'), ('FROM_80_TO_100', 'Αναπηρία 80% και άνω')], default=None, help_text='Λόγοι Υγείας Ιδίων', max_length=32, null=True)),
                ('health_issues_partner', models.CharField(choices=[('FROM_50_TO_66', 'Αναπηρία 50-66%'), ('FROM_67_TO_79', 'Αναπηρία 67-79%'), ('FROM_80_TO_100', 'Αναπηρία 80% και άνω')], default=None, help_text='Λόγοι Υγείας Συζύγου', max_length=32, null=True)),
                ('health_issues_child', models.CharField(choices=[('FROM_50_TO_66', 'Αναπηρία 50-66%'), ('FROM_67_TO_79', 'Αναπηρία 67-79%'), ('FROM_80_TO_100', 'Αναπηρία 80% και άνω')], default=None, help_text='Λόγοι Υγείας Τέκνων', max_length=32, null=True)),
                ('health_issues_parent', models.CharField(choices=[('FROM_50_TO_66', 'Αναπηρία 50-66%'), ('FROM_67_TO_100', 'Αναπηρία 67% και άνω')], default=None, help_text='Λόγοι Υγείας Γονέων', max_length=32, null=True)),
                ('health_issues_sibling', models.CharField(choices=[('FROM_67_TO_100', 'Αναπηρία 67% και άνω')], default=None, help_text='Λόγοι Υγείας Αδελφών', max_length=32, null=True)),
                ('ivf_treatment', models.BooleanField(default=False, help_text='Θεραπεία Εξωσωματικής Γονιμοποίησης')),
                ('postgraduate_studies', models.BooleanField(default=False, help_text='Μεταπτυχιακές Σπουδές')),
                ('has_many_children', models.BooleanField(default=False, help_text='Πολύτεκνος')),
                ('has_child_with_disabilities_67', models.BooleanField(default=False, help_text='Γονέας τέκνου με ποσοστό αναπηρίας 67%')),
                ('has_illness', models.BooleanField(default=False, help_text='Ασθένεια')),
                ('effective_school', models.ForeignKey(help_text='Σχολείο που Υπηρετεί', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_effective_school_submission', to='commons.school')),
                ('locality_municipality', models.ForeignKey(default=None, help_text='Δήμος Εντοπιότητας', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_locality_municipality_submissions', to='commons.municipality')),
                ('parents_residence_municipality', models.ForeignKey(default=None, help_text='Δήμος Διαμονής Γονέων', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_parents_residence_municipality_submission', to='commons.municipality')),
                ('postgraduate_studies_municipality', models.ForeignKey(default=None, help_text='Δήμος Σπουδών', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_postgraduate_studies_municipality_submission', to='commons.municipality')),
                ('school', models.ForeignKey(help_text='Οργανική Θέση', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_school_submission', to='commons.school')),
                ('sibling_residence_municipality', models.ForeignKey(default=None, help_text='Δήμος Διαμονής Αδελφού-(ων)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_sibling_residence_municipality_submission', to='commons.municipality')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('work_together_municipality', models.ForeignKey(default=None, help_text='Δήμος Συνυπηρέτησης', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_work_together_municipality_submission', to='commons.municipality')),
            ],
        ),
        migrations.CreateModel(
            name='SubmissionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_date', models.DateTimeField(auto_now_add=True)),
                ('comment', models.CharField(blank=True, max_length=255, null=True)),
                ('related_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='submissions.submission')),
                ('triggered_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='submissionevent',
            index=models.Index(fields=['event_date', 'related_to', 'triggered_by'], name='submissions_event_d_74c191_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['user'], name='submissions_user_id_ca3960_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['status'], name='submissions_status_c2b4f2_idx'),
        ),
    ]
